### ISSUE TITLE
OpenGLの基礎学習

### ISSUE THREAD

**Issue by morir** [Sunkenship1995/GLUT#1]
開発環境の構築やサンプルの実装を行い、テーマの実現に向けた具体化を図る。

- 開発環境は以下とする。
  - 言語：C++
  - IDE：VisualStudio
  - コード管理：gitHub
- サンプル実装（ [GLUTによる「手抜き」OpenGL入門](https://tokoik.github.io/opengl/libglut.html) ）
  - [x] 演習1
  - [x] 演習2
  - [x] 演習3
  - [x] 演習4
  - [x] 演習5
  - [x] 演習6
  - [x] 演習7
  - [x] 演習8
  - [x] 演習9
  - [x] 演習10
  - [x] 演習11
  - [x] 演習12

**Comment by morir** [comment]
Sunkenshipがチェックを付けて進捗更新していって、
全チェックが付いたらokaryuがIssueをクローズするっていうのはどうですか？

**Comment by Sunkenship1995** [comment]
森さんとSkype通話での画面共有の確認に成功

**Comment by Sunkenship1995** [comment]
@okaryu569 
学習が終了したので
closedお願いします。

**Comment by ghost** [comment]
一通り行ったことで、方向性や実現可能性も見えてきたので、本issue は CLOSE とします。

@Sunkenship1995 
他のチケットも、作業→チケット更新→CLOSE依頼→CLOSEって流れでお願いします！

また、FC の Redmine からリンクしました。
それに伴い、詳細はこっちをみてくださいとしている手前、多少体裁を整えました。
今後はこの作業も Sunkenship1995 にやってほしいです。
